plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
    id 'com.matthewprenger.cursegradle' version '1.5.0'
    id "com.modrinth.minotaur" version "2.+"
}

apply plugin: "com.modrinth.minotaur"
apply plugin: "com.matthewprenger.cursegradle"

base {
    archivesName = rootProject.archives_base_name
}

version = rootProject.mod_version
group = rootProject.maven_group

repositories {
    maven { url "https://maven.pitan76.net/" }
    maven { url "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}

if (System.getenv("CURSEFORGE_TOKEN") != null) {
    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = '1055171'
            changelog = 'port to 1.26.1'
            releaseType = 'release'
            addGameVersion "Fabric"
            addGameVersion '26.1'

            mainArtifact(tasks.jar)
        }
        options {
            forgeGradleIntegration = false
        }
    }

}

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = 'WcHRLVFE'
        versionNumber = rootProject.mod_version + "-" + "fabric"
        gameVersions = ['26.1']
        versionType = 'release'
        uploadFile = tasks.jar
        changelog = 'port to 1.26.1'
        loaders = ["fabric"]
    }
}


processResources {
    inputs.property "version", rootProject.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": rootProject.version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion

    options.release = 25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 25
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    base.archivesName = project.archives_base_name
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + "fabric"
            version = project.version.toString().replace("-" + "fabric", "")
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/PTOM76/maven")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
