org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.1
enabled_platforms=fabric

archives_base_name=compatdatapacks76
mod_version=1.0.16.261
maven_group=net.pitan76

# https://fabricmc.net/develop/
fabric_loader_version=0.18.4

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=26.1-62.0.1

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.1-beta
