modLoader="javafml"
loaderVersion="[50,)"
license="MIT"
issueTrackerURL="https://github.com/PTOM76/CompatDatapacks/issues"

[[mods]]
modId="compatdatapacks"
version="${version}"
displayName="CompatDatapacks"
displayURL="https://curseforge.com/minecraft/mc-mods/compat-datapacks"
logoFile="icon.png"
authors="PitaQ"
description='''
The mod enables backward compatibility for your Minecraft data packs.
'''

[[dependencies.compatdatapacks]]
   modId="neoforge"
   mandatory=true
   versionRange="[50,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.compatdatapacks]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"

[[mixins]]
config = "compatdatapacks-common.mixins.json"
