modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/PTOM76/CompatDatapacks/issues"

[[mods]]
modId="compatdatapacks76"
version="${version}"
displayName="CompatDatapacks"
displayURL="https://curseforge.com/minecraft/mc-mods/compat-datapacks76"
logoFile="icon.png"
authors="PitaQ"
description='''
The mod enables backward compatibility for datapacks.
'''

[[dependencies.compatdatapacks76]]
   modId="neoforge"
   type = "required"
   versionRange="[21.0.40-beta,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.compatdatapacks76]]
   modId="minecraft"
   type = "required"
   versionRange="[1.21,)"
   ordering="NONE"
   side="BOTH"

[[mixins]]
config = "compatdatapacks76-common.mixins.json"
